### ISSUE TITLE
Eager instantiate `@JdbiRepository`

### ISSUE THREAD

**Issue by mustafashabib** [xvik/dropwizard-guicey-ext#33]
Hi there

I'm debugging an issue where the first request to a repository is "slow" on our app, and it seems to be caused by the `JdbiRepository` being instantiated for the first time. Is there a way to force these objects to be created at startup?

My current solution requires that I make a request to each repository through its public API during a `Managed` object's startup phase, but that seems messy. Just wondering what you'd recommend here.

Thanks

**Comment by xvik** [comment]
Hi!

Indeed repository proxy is lazy: https://github.com/xvik/dropwizard-guicey-ext/blob/master/guicey-jdbi3/src/main/java/ru/vyarus/guicey/jdbi3/installer/repository/RepositoryInstaller.java#L71 
A real sql proxy object is constructed on [the first call](https://github.com/xvik/dropwizard-guicey-ext/blob/043cdd183ea68f95564d4dae94b92d2e18b1527b/guicey-jdbi3/src/main/java/ru/vyarus/guicey/jdbi3/installer/repository/sql/SqlObjectProvider.java#L43).

Laziness was intentional to avoid jdbi misconfiguration (to use all registered custom mappers).

Still, delayed init should be a feature of the module itself. I didn't think it could take a considerable amount of time (become a problem).

For manual init, I can only suggest adding some base interface with a common method, so all repositories could extend it. Initializer Managed object could use guicey info object to resolve all repositories:

```java
public class RepoInit implements Managed {
    @Inject GuiceyConfigurationInfo guiceyInfo;
    @Inject Injector injector;

    @InTransaction
    public void start() {
        // all installed repositories
        List<Class> repos = guiceyInfo.getExtensions(ResourceInstaller.class);
        // obtain each repo from context and call init 
        repos.forEach it -> ((BaseRepoClass)injector.getInstance(it)).commonInitMethod()
    }
}
```

NOTE: just in case, `guiceyInfo.getExtensions` will also return possibly disabled extensions, but I assume I will not disable repositories in tests (code counting enabled state would be a bit longer).

Something like this should work.

TODO

- [ ] Option to eager init repositories on startup

**Comment by xvik** [comment]
New bundle method added to enable eager proxies initialization: `JdbiBundle.withEagerInitialization()`
