### ISSUE TITLE
Cannot access a member of the interface ... with modifiers "public"

### ISSUE THREAD

**Issue by mustafashabib** [xvik/dropwizard-guicey-ext#4]
I have guicey working for the most part but seeing a curious issue:

```java 
@JdbiRepository
public interface CrudRepository {
insert(String name);
update(String name);

/*convoluted example*/
   default T save(String name) {
       if(name != "test") {
         insert(name);
       } else return update(name);
    }
}

@JdbiRepository
public interface BaseRepository  extends CrudRepository {
@SqlUpdate("insert into table(name) values(:name)")
int insert(String name);
@SqlUpdate("update table set name = :name")
int update(String name);
}

@JdbiRepository
public interface MyRepository extends CrudRepository {
@SqlUpdate("insert into second_table(name) values(:name)")
int insert(String name);
@SqlUpdate("update second_table set name = :name")
int update(String name);
}
class ServiceBase
{
 protected BaseRepository baseRepo;
@Inject 
public ServiceBase(BaseRepository baseRepo) {
  this.baseRepo = baseRepo;
 }

@InTransaction
public void baseMethod() {
  baseRepo.save("test");
  baseRepo.save("test2");
}
}

public class MyService extends ServiceBase  
{
  protected MyRepository myRepo;
  @Inject
  public MyService(MyRepository myRepo, BaseRepository baseRepo) {
    super(baseRepo);
    this.myRepo = myRepo;
  }

@InTransaction
public void doSomethingComplex() {
  baseMethod("test");
  myRepo.save("test 3");
}
```

I believe this setup is wrong somehow but unclear how. When I call `doSomethingComplex` in my service layer, the exception I see is:

```shell
org.jdbi.v3.core.extension.NoSuchExtensionException: Extension not found: interface CrudRepository
! at ru.vyarus.guicey.jdbi3.installer.repository.sql.SqlObjectProvider.lambda$create$0(SqlObjectProvider.java:63)
! at java.base/java.util.Optional.orElseThrow(Optional.java:408)
! at ru.vyarus.guicey.jdbi3.installer.repository.sql.SqlObjectProvider.create(SqlObjectProvider.java:63)
! at ru.vyarus.guicey.jdbi3.installer.repository.sql.SqlObjectProvider.get(SqlObjectProvider.java:46)
! at ru.vyarus.guicey.jdbi3.installer.repository.RepositoryInstaller.lambda$install$0(RepositoryInstaller.java:64)
! at ru.vyarus.guicey.jdbi3.tx.aop.TransactionalInterceptor.lambda$invoke$0(TransactionalInterceptor.java:53)
! at ru.vyarus.guicey.jdbi3.tx.TransactionTemplate.inCurrentTransaction(TransactionTemplate.java:96)
! at ru.vyarus.guicey.jdbi3.tx.TransactionTemplate.inTransaction(TransactionTemplate.java:69)
! at ru.vyarus.guicey.jdbi3.tx.aop.TransactionalInterceptor.invoke(TransactionalInterceptor.java:51)
```

So... what have I done incorrectly?

**Comment by xvik** [comment]
`@JdbiRepository` should be used only on actual repositories which you are going to use as guice beans. Base interfaces (`CrudRepository` and `BaseRepository`) should not be annotated (you should see in console logs that base classes are mentioned as installed repositories). If you remove redundant annotations everything will work.

Now the interesting part - explanation. Repositories are actually called with guice AOP: for each registered repository bean interceptor registered like this `binder.bindInterceptor(Matchers.subclassesOf(type)...` which translates the call to actual jdbi proxy. And so when you annotate your base interface `CrudRepostory`, the interceptor is registered like this `binder.bindInterceptor(Matchers.subclassesOf(CrudRepository.class)...` and that means that this interceptor will be always called for any other repository extending crud interface before correct interceptor.

This is not a bug, because interceptor declaration actually targets dynamic proxy class (without this guice aop would not work) and so it must target subclasses of repository interface (`Matchers.subclassesOf(type)`). The only thing I can do here is adding an explicit check for redundant annotations to fail server startup with a good explanation message.

**Comment by xvik** [comment]
At least exception above was definitely caused by `@JdbiRepository` on common interfaces. Most likely coincidence, but if you had other exceptions it could be related to them.
